### ISSUE TITLE
[bug] can not yarn unit

### ISSUE THREAD

**Issue by StevenYuysy** [eddyerburgh/vue-test-utils-jest-example#1]
## steps to reproduce

- git clone https://github.com/eddyerburgh/vue-test-utils-jest-example.git
- cd vue-test-utils-jest-example
- yarn 
- yarn unit

## expected behavior

test pass

## actual behavior

```bash
yarn unit
yarn unit v0.23.4
$ jest 
 PASS  test/specs/Message.spec.js
 FAIL  test/specs/List.spec.js
  ● Test suite failed to run

    Couldn't find preset "es2015" relative to directory "/Volumes/DevelopOnly/Github/vue-test-utils-jest-example"
      
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
          at Array.map (<anonymous>)

 FAIL  test/specs/MessageToggle.spec.js
  ● Test suite failed to run

    Couldn't find preset "es2015" relative to directory "/Volumes/DevelopOnly/Github/vue-test-utils-jest-example"
      
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
          at Array.map (<anonymous>)

Test Suites: 2 failed, 1 passed, 3 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        4.532s
Ran all test suites.
error Command failed with exit code 1.
```

## description

same with `npm install && npm run unit`

- OS version: macOS 10.12.6
- yarn version: v0.23.4
- node version: v8.4.0
- npm version: 5.3.0

**Comment by eddyerburgh** [comment]
Thanks for the bug report 😃 

I've fixed the issue, babel-preset-es2015 wasn't listed in the dev dependencies

I'm going to add the project to circle so this doesn't happen again 👌

**Comment by StevenYuysy** [comment]
I think that we can use `babel-preset-env` instead of ` babel-preset-es2015`, but can not figure out why this test require `es2015`

**Comment by eddyerburgh** [comment]
I think it's a bug with jest-vue that was fixed. If you install the latest jest-vue 0.5.3 it should be fixed

**Comment by StevenYuysy** [comment]
Close by d78617dab52ae1bad4c5794de44fe23e10fef28e
